### ISSUE TITLE
Version 1 (epic)

### ISSUE THREAD

**Issue by curran** [datavis-tech/pleth#1]
* [ ] Get canvas rendering working for geo shapes, using a technique like this one https://bl.ocks.org/mbostock/6252418
 * [ ] Import/simplify GADM boundary files
 * [ ] Join with some sample data to produce a choropleth example
 * [ ] Implement drill down
 * [ ] Implement drill up
 * [ ] Implement breadcrumbs utilities
 * [ ] Add a labeling layer for administrative regions (SVG)
 * [ ] Add a labeling layer for major cities (SVG)
